version: "3.7"

networks:
  jupyter:
    driver: overlay
    attachable: true
    name: jupyter

services:
  minimal:
    image: jupyter/minimal-notebook
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"

  scipy:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"

  tensorflow:
    image: jupyter/tensorflow-notebook
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"

  wbd:
    image: myjupyter:wbd
    build:
      context: ./wbd-build
      dockerfile: Dockerfile.wbd
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"
